program saxpytest
	use saxpykernel
	use cudafor
	implicit none
	integer, parameter :: N = 128*1024*1024
	integer, parameter :: blocksize=256
	real :: x(N), y(N), a
	real, device :: x_d(N), y_d(N)
	type(dim3) :: grid, block

	grid = dim3(ceiling(real(N)/blocksize),1,1)
	block = dim3(blocksize,1,1)

	x = 1.0; y = 2.0; a = 2.0
	x_d = x
	y_d = y
	call saxpy<<<grid,block>>>(x_d, y_d, a)
	y = y_d
	if (all(y == 4)) write (*,*) 'Test Passed'
end program saxpytest